class Country
  include DataMapper::Resource
  
  def self.default_repository_name #here we use the users_db for the User objects
    :default
  end

  property :id, Serial, :key => true
  property :iso_code, String, :max => 3
  property :name, String
  property :created_at, DateTime
  property :updated_at, DateTime
  has n :provinces, :model => Province
  
  def begin
    self.create(:iso_code => 'AD', :name => 'Andorra')
    self.create(:iso_code => 'AE', :name => 'United Arab Emirates')
    self.create(:iso_code => 'AF', :name => 'Afghanistan')
    self.create(:iso_code => 'AG', :name => 'Antigua and Barbuda')
    self.create(:iso_code => 'AI', :name => 'Anguilla')
    self.create(:iso_code => 'AL', :name => 'Albania')
    self.create(:iso_code => 'AM', :name => 'Armenia')
    self.create(:iso_code => 'AO', :name => 'Angola')
    self.create(:iso_code => 'AQ', :name => 'Antarctica')
    self.create(:iso_code => 'AR', :name => 'Argentina')
    self.create(:iso_code => 'AS', :name => 'American Samoa')
    self.create(:iso_code => 'AT', :name => 'Austria')
    self.create(:iso_code => 'AU', :name => 'Australia')
    self.create(:iso_code => 'AW', :name => 'Aruba')
    self.create(:iso_code => 'AX', :name => 'Åland Islands')
    self.create(:iso_code => 'AZ', :name => 'Azerbaijan')
    self.create(:iso_code => 'BA', :name => 'Bosnia and Herzegovina')
    self.create(:iso_code => 'BB', :name => 'Barbados')
    self.create(:iso_code => 'BD', :name => 'Bangladesh')
    self.create(:iso_code => 'BE', :name => 'Belgium')
    self.create(:iso_code => 'BF', :name => 'Burkina Faso')
    self.create(:iso_code => 'BG', :name => 'Bulgaria')
    self.create(:iso_code => 'BH', :name => 'Bahrain')
    self.create(:iso_code => 'BI', :name => 'Burundi')
    self.create(:iso_code => 'BJ', :name => 'Benin')
    self.create(:iso_code => 'BL', :name => 'Saint Barthélemy')
    self.create(:iso_code => 'BM', :name => 'Bermuda')
    self.create(:iso_code => 'BN', :name => 'Brunei Darussalam')
    self.create(:iso_code => 'BO', :name => 'Bolivia')
    self.create(:iso_code => 'BQ', :name => 'Caribbean Netherlands ')
    self.create(:iso_code => 'BR', :name => 'Brazil')
    self.create(:iso_code => 'BS', :name => 'Bahamas')
    self.create(:iso_code => 'BT', :name => 'Bhutan')
    self.create(:iso_code => 'BV', :name => 'Bouvet Island')
    self.create(:iso_code => 'BW', :name => 'Botswana')
    self.create(:iso_code => 'BY', :name => 'Belarus')
    self.create(:iso_code => 'BZ', :name => 'Belize')
    self.create(:iso_code => 'CA', :name => 'Canada')
    self.create(:iso_code => 'CC', :name => 'Cocos (Keeling) Islands')
    self.create(:iso_code => 'CD', :name => 'Congo, Democratic Republic of')
    self.create(:iso_code => 'CF', :name => 'Central African Republic')
    self.create(:iso_code => 'CG', :name => 'Congo')
    self.create(:iso_code => 'CH', :name => 'Switzerland')
    self.create(:iso_code => 'CI', :name => 'Côte Ivoire')
    self.create(:iso_code => 'CK', :name => 'Cook Islands')
    self.create(:iso_code => 'CL', :name => 'Chile')
    self.create(:iso_code => 'CM', :name => 'Cameroon')
    self.create(:iso_code => 'CN', :name => 'China')
    self.create(:iso_code => 'CO', :name => 'Colombia')
    self.create(:iso_code => 'CR', :name => 'Costa Rica')
    self.create(:iso_code => 'CU', :name => 'Cuba')
    self.create(:iso_code => 'CV', :name => 'Cape Verde')
    self.create(:iso_code => 'CW', :name => 'Curaçao')
    self.create(:iso_code => 'CX', :name => 'Christmas Island')
    self.create(:iso_code => 'CY', :name => 'Cyprus')
    self.create(:iso_code => 'CZ', :name => 'Czech Republic')
    self.create(:iso_code => 'DE', :name => 'Germany')
    self.create(:iso_code => 'DJ', :name => 'Djibouti')
    self.create(:iso_code => 'DK', :name => 'Denmark')
    self.create(:iso_code => 'DM', :name => 'Dominica')
    self.create(:iso_code => 'DO', :name => 'Dominican Republic')
    self.create(:iso_code => 'DZ', :name => 'Algeria')
    self.create(:iso_code => 'EC', :name => 'Ecuador')
    self.create(:iso_code => 'EE', :name => 'Estonia')
    self.create(:iso_code => 'EG', :name => 'Egypt')
    self.create(:iso_code => 'EH', :name => 'Western Sahara')
    self.create(:iso_code => 'ER', :name => 'Eritrea')
    self.create(:iso_code => 'ES', :name => 'Spain')
    self.create(:iso_code => 'ET', :name => 'Ethiopia')
    self.create(:iso_code => 'FI', :name => 'Finland')
    self.create(:iso_code => 'FJ', :name => 'Fiji')
    self.create(:iso_code => 'FK', :name => 'Falkland Islands')
    self.create(:iso_code => 'FM', :name => 'Micronesia, Federated States of')
    self.create(:iso_code => 'FO', :name => 'Faroe Islands')
    self.create(:iso_code => 'FR', :name => 'France')
    self.create(:iso_code => 'GA', :name => 'Gabon')
    self.create(:iso_code => 'GB', :name => 'United Kingdom')
    self.create(:iso_code => 'GD', :name => 'Grenada')
    self.create(:iso_code => 'GE', :name => 'Georgia')
    self.create(:iso_code => 'GF', :name => 'French Guiana')
    self.create(:iso_code => 'GG', :name => 'Guernsey')
    self.create(:iso_code => 'GH', :name => 'Ghana')
    self.create(:iso_code => 'GI', :name => 'Gibraltar')
    self.create(:iso_code => 'GL', :name => 'Greenland')
    self.create(:iso_code => 'GM', :name => 'Gambia')
    self.create(:iso_code => 'GN', :name => 'Guinea')
    self.create(:iso_code => 'GP', :name => 'Guadeloupe')
    self.create(:iso_code => 'GQ', :name => 'Equatorial Guinea')
    self.create(:iso_code => 'GR', :name => 'Greece')
    self.create(:iso_code => 'GS', :name => 'South Georgia and the South Sandwich Islands')
    self.create(:iso_code => 'GT', :name => 'Guatemala')
    self.create(:iso_code => 'GU', :name => 'Guam')
    self.create(:iso_code => 'GW', :name => 'Guinea-Bissau')
    self.create(:iso_code => 'GY', :name => 'Guyana')
    self.create(:iso_code => 'HK', :name => 'Hong Kong')
    self.create(:iso_code => 'HM', :name => 'Heard and McDonald Islands')
    self.create(:iso_code => 'HN', :name => 'Honduras')
    self.create(:iso_code => 'HR', :name => 'Croatia')
    self.create(:iso_code => 'HT', :name => 'Haiti')
    self.create(:iso_code => 'HU', :name => 'Hungary')
    self.create(:iso_code => 'ID', :name => 'Indonesia')
    self.create(:iso_code => 'IE', :name => 'Ireland')
    self.create(:iso_code => 'IL', :name => 'Israel')
    self.create(:iso_code => 'IM', :name => 'Isle of Man')
    self.create(:iso_code => 'IN', :name => 'India')
    self.create(:iso_code => 'IO', :name => 'British Indian Ocean Territory')
    self.create(:iso_code => 'IQ', :name => 'Iraq')
    self.create(:iso_code => 'IR', :name => 'Iran')
    self.create(:iso_code => 'IS', :name => 'Iceland')
    self.create(:iso_code => 'IT', :name => 'Italy')
    self.create(:iso_code => 'JE', :name => 'Jersey')
    self.create(:iso_code => 'JM', :name => 'Jamaica')
    self.create(:iso_code => 'JO', :name => 'Jordan')
    self.create(:iso_code => 'JP', :name => 'Japan')
    self.create(:iso_code => 'KE', :name => 'Kenya')
    self.create(:iso_code => 'KG', :name => 'Kyrgyzstan')
    self.create(:iso_code => 'KH', :name => 'Cambodia')
    self.create(:iso_code => 'KI', :name => 'Kiribati')
    self.create(:iso_code => 'KM', :name => 'Comoros')
    self.create(:iso_code => 'KN', :name => 'Saint Kitts and Nevis')
    self.create(:iso_code => 'KP', :name => 'North Korea')
    self.create(:iso_code => 'KR', :name => 'South Korea')
    self.create(:iso_code => 'KW', :name => 'Kuwait')
    self.create(:iso_code => 'KY', :name => 'Cayman Islands')
    self.create(:iso_code => 'KZ', :name => 'Kazakhstan')
    self.create(:iso_code => 'LA', :name => 'Laos')
    self.create(:iso_code => 'LB', :name => 'Lebanon')
    self.create(:iso_code => 'LC', :name => 'Saint Lucia')
    self.create(:iso_code => 'LI', :name => 'Liechtenstein')
    self.create(:iso_code => 'LK', :name => 'Sri Lanka')
    self.create(:iso_code => 'LR', :name => 'Liberia')
    self.create(:iso_code => 'LS', :name => 'Lesotho')
    self.create(:iso_code => 'LT', :name => 'Lithuania')
    self.create(:iso_code => 'LU', :name => 'Luxembourg')
    self.create(:iso_code => 'LV', :name => 'Latvia')
    self.create(:iso_code => 'LY', :name => 'Libya')
    self.create(:iso_code => 'MA', :name => 'Morocco')
    self.create(:iso_code => 'MC', :name => 'Monaco')
    self.create(:iso_code => 'MD', :name => 'Moldova')
    self.create(:iso_code => 'ME', :name => 'Montenegro')
    self.create(:iso_code => 'MF', :name => 'Saint-Martin (France)')
    self.create(:iso_code => 'MG', :name => 'Madagascar')
    self.create(:iso_code => 'MH', :name => 'Marshall Islands')
    self.create(:iso_code => 'MK', :name => 'Macedonia')
    self.create(:iso_code => 'ML', :name => 'Mali')
    self.create(:iso_code => 'MM', :name => 'Myanmar')
    self.create(:iso_code => 'MN', :name => 'Mongolia')
    self.create(:iso_code => 'MO', :name => 'Macau')
    self.create(:iso_code => 'MP', :name => 'Northern Mariana Islands')
    self.create(:iso_code => 'MQ', :name => 'Martinique')
    self.create(:iso_code => 'MR', :name => 'Mauritania')
    self.create(:iso_code => 'MS', :name => 'Montserrat')
    self.create(:iso_code => 'MT', :name => 'Malta')
    self.create(:iso_code => 'MU', :name => 'Mauritius')
    self.create(:iso_code => 'MV', :name => 'Maldives')
    self.create(:iso_code => 'MW', :name => 'Malawi')
    self.create(:iso_code => 'MX', :name => 'Mexico')
    self.create(:iso_code => 'MY', :name => 'Malaysia')
    self.create(:iso_code => 'MZ', :name => 'Mozambique')
    self.create(:iso_code => 'NA', :name => 'Namibia')
    self.create(:iso_code => 'NC', :name => 'New Caledonia')
    self.create(:iso_code => 'NE', :name => 'Niger')
    self.create(:iso_code => 'NF', :name => 'Norfolk Island')
    self.create(:iso_code => 'NG', :name => 'Nigeria')
    self.create(:iso_code => 'NI', :name => 'Nicaragua')
    self.create(:iso_code => 'NL', :name => 'The Netherlands')
    self.create(:iso_code => 'NO', :name => 'Norway')
    self.create(:iso_code => 'NP', :name => 'Nepal')
    self.create(:iso_code => 'NR', :name => 'Nauru')
    self.create(:iso_code => 'NU', :name => 'Niue')
    self.create(:iso_code => 'NZ', :name => 'New Zealand')
    self.create(:iso_code => 'OM', :name => 'Oman')
    self.create(:iso_code => 'PA', :name => 'Panama')
    self.create(:iso_code => 'PE', :name => 'Peru')
    self.create(:iso_code => 'PF', :name => 'French Polynesia')
    self.create(:iso_code => 'PG', :name => 'Papua New Guinea')
    self.create(:iso_code => 'PH', :name => 'Philippines')
    self.create(:iso_code => 'PK', :name => 'Pakistan')
    self.create(:iso_code => 'PL', :name => 'Poland')
    self.create(:iso_code => 'PM', :name => 'St. Pierre and Miquelon')
    self.create(:iso_code => 'PN', :name => 'Pitcairn')
    self.create(:iso_code => 'PR', :name => 'Puerto Rico')
    self.create(:iso_code => 'PS', :name => 'Palestine, State of')
    self.create(:iso_code => 'PT', :name => 'Portugal')
    self.create(:iso_code => 'PW', :name => 'Palau')
    self.create(:iso_code => 'PY', :name => 'Paraguay')
    self.create(:iso_code => 'QA', :name => 'Qatar')
    self.create(:iso_code => 'RE', :name => 'Réunion')
    self.create(:iso_code => 'RO', :name => 'Romania')
    self.create(:iso_code => 'RS', :name => 'Serbia')
    self.create(:iso_code => 'RU', :name => 'Russian Federation')
    self.create(:iso_code => 'RW', :name => 'Rwanda')
    self.create(:iso_code => 'SA', :name => 'Saudi Arabia')
    self.create(:iso_code => 'SB', :name => 'Solomon Islands')
    self.create(:iso_code => 'SC', :name => 'Seychelles')
    self.create(:iso_code => 'SD', :name => 'Sudan')
    self.create(:iso_code => 'SE', :name => 'Sweden')
    self.create(:iso_code => 'SG', :name => 'Singapore')
    self.create(:iso_code => 'SH', :name => 'Saint Helena')
    self.create(:iso_code => 'SI', :name => 'Slovenia')
    self.create(:iso_code => 'SJ', :name => 'Svalbard and Jan Mayen Islands')
    self.create(:iso_code => 'SK', :name => 'Slovakia')
    self.create(:iso_code => 'SL', :name => 'Sierra Leone')
    self.create(:iso_code => 'SM', :name => 'San Marino')
    self.create(:iso_code => 'SN', :name => 'Senegal')
    self.create(:iso_code => 'SO', :name => 'Somalia')
    self.create(:iso_code => 'SR', :name => 'Suriname')
    self.create(:iso_code => 'SS', :name => 'South Sudan')
    self.create(:iso_code => 'ST', :name => 'Sao Tome and Principe')
    self.create(:iso_code => 'SV', :name => 'El Salvador')
    self.create(:iso_code => 'SX', :name => 'Sint Maarten (Dutch part)')
    self.create(:iso_code => 'SY', :name => 'Syria')
    self.create(:iso_code => 'SZ', :name => 'Swaziland')
    self.create(:iso_code => 'TC', :name => 'Turks and Caicos Islands')
    self.create(:iso_code => 'TD', :name => 'Chad')
    self.create(:iso_code => 'TF', :name => 'French Southern Territories')
    self.create(:iso_code => 'TG', :name => 'Togo')
    self.create(:iso_code => 'TH', :name => 'Thailand')
    self.create(:iso_code => 'TJ', :name => 'Tajikistan')
    self.create(:iso_code => 'TK', :name => 'Tokelau')
    self.create(:iso_code => 'TL', :name => 'Timor-Leste')
    self.create(:iso_code => 'TM', :name => 'Turkmenistan')
    self.create(:iso_code => 'TN', :name => 'Tunisia')
    self.create(:iso_code => 'TO', :name => 'Tonga')
    self.create(:iso_code => 'TR', :name => 'Turkey')
    self.create(:iso_code => 'TT', :name => 'Trinidad and Tobago')
    self.create(:iso_code => 'TV', :name => 'Tuvalu')
    self.create(:iso_code => 'TW', :name => 'Taiwan')
    self.create(:iso_code => 'TZ', :name => 'Tanzania')
    self.create(:iso_code => 'UA', :name => 'Ukraine')
    self.create(:iso_code => 'UG', :name => 'Uganda')
    self.create(:iso_code => 'UM', :name => 'United States Minor Outlying Islands')
    self.create(:iso_code => 'US', :name => 'United States')
    self.create(:iso_code => 'UY', :name => 'Uruguay')
    self.create(:iso_code => 'UZ', :name => 'Uzbekistan')
    self.create(:iso_code => 'VA', :name => 'Vatican')
    self.create(:iso_code => 'VC', :name => 'Saint Vincent and the Grenadines')
    self.create(:iso_code => 'VE', :name => 'Venezuela')
    self.create(:iso_code => 'VG', :name => 'Virgin Islands (British)')
    self.create(:iso_code => 'VI', :name => 'Virgin Islands (U.S.)')
    self.create(:iso_code => 'VN', :name => 'Vietnam')
    self.create(:iso_code => 'VU', :name => 'Vanuatu')
    self.create(:iso_code => 'WF', :name => 'Wallis and Futuna Islands')
    self.create(:iso_code => 'WS', :name => 'Samoa')
    self.create(:iso_code => 'YE', :name => 'Yemen')
    self.create(:iso_code => 'YT', :name => 'Mayotte')
    self.create(:iso_code => 'ZA', :name => 'South Africa')
    self.create(:iso_code => 'ZM', :name => 'Zambia')
    self.create(:iso_code => 'ZW', :name => 'Zimbabwe')
  end
end

